//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCBankApps.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABCBank : DbContext
    {
        public ABCBank()
            : base("name=ABCBank")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountUser> AccountUsers { get; set; }
        public DbSet<CustomersAcct> CustomersAccts { get; set; }
        public DbSet<Deposit> Deposits { get; set; }
        public DbSet<StaffDetail> StaffDetails { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<Withdrawl> Withdrawls { get; set; }
    }
}
