//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCBankApps.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class AccountUser
    {
        public string cAuLd { get; set; }

        [Required(ErrorMessage="* Enter email address")]
        [Display(Name="Email Address")]
        public string nEmail { get; set; }

        [Required(ErrorMessage = "* Enter Password")]
        [Display(Name = "Password")]
        public string nPassword { get; set; }

        public string nPasswordSalt { get; set; }
    }
}
