//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCBankApps.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CustomersAcct
    {
        public CustomersAcct()
        {
            this.Withdrawls = new HashSet<Withdrawl>();
            this.Deposits = new HashSet<Deposit>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        [Required(ErrorMessage="Account No. Required")]
        [Display(Name="Account Number")]
        public int iAcNo { get; set; }

        [Required(ErrorMessage = "Enter Customer's firstName")]
        [Display(Name = "First Name")]
        public string vCusName { get; set; }

        [Required(ErrorMessage = "Enter Customer's LastName")]
        [Display(Name = "Last Name")]
        public string vCusSurName { get; set; }

        [Required(ErrorMessage = "Enter Gender")]
        [Display(Name = "Gender")]
        public string cSex { get; set; }

        [Required(ErrorMessage = "Enter Customer's Home Address")]
        [Display(Name = "Home Address")]
        public string vAddress { get; set; }

         [Display(Name = "Opening Date")]
        public Nullable<System.DateTime> dDate { get; set; }

        [Required(ErrorMessage = "Amount Required")]
        [Range(1000,double.MaxValue,ErrorMessage="price must be between N1000 and above")]
        [Display(Name = "Opening Balance")]
        [DataType(DataType.Currency)]
        public decimal mBal { get; set; }

        [Required(ErrorMessage = "Enter Account officer Id")]
        [Display(Name = "Account Officier Id")]
        public string staffid { get; set; }
    
        public virtual ICollection<Withdrawl> Withdrawls { get; set; }
        public virtual ICollection<Deposit> Deposits { get; set; }
        public virtual StaffDetail StaffDetail { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
