//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCBankApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDetail
    {
        public StaffDetail()
        {
            this.CustomersAccts = new HashSet<CustomersAcct>();
        }
    
        public string staffId { get; set; }
        public string staffName { get; set; }
        public string staffLastName { get; set; }
        public string cPhoneNo { get; set; }
        public Nullable<int> iAge { get; set; }
        public string cSex { get; set; }
    
        public virtual ICollection<CustomersAcct> CustomersAccts { get; set; }
    }
}
