//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCBankApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TansId { get; set; }
        public int iacno { get; set; }
        public decimal amount { get; set; }
        public string AmtInWords { get; set; }
        public string TransType { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
    
        public virtual CustomersAcct CustomersAcct { get; set; }
    }
}
