//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCBankApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Withdrawl
    {
        public int SlipNo { get; set; }
        public Nullable<int> iAcNo { get; set; }
        public decimal Amtwithdraw { get; set; }
        public string Amtinwords { get; set; }
        public Nullable<System.DateTime> DateOfWith { get; set; }
    
        public virtual CustomersAcct CustomersAcct { get; set; }
    }
}
